### ISSUE TITLE
statusbar percent.max

### ISSUE THREAD

**Issue by stemicha** [STATWORX/helfRlein#25]
Dear STATWORX-team,

unfortunately in the newer releases the _percent.max_ parameter is missing in the **statusbar()** function. It is replaced by _width_.

In terms of downward compatibility of scripts it would be nice to leave _percent.max_ as redundant parameter inside the function.

thanks 
Stephan

**Comment by Dschaykib** [comment]
I will have a look at it and will add it again.

**Comment by Dschaykib** [comment]
the fix is at the moment only on the dev branch, since there is an other issue with the ubuntu test set up, it will take a while until I will merge it onto the master branch.

Thanks for mentioning the problem and if you find anything else, let me know!
BTW: The reason why is changed the name was due to a styling process for lintr.
